<#
.SYNOPSIS
    Regenerates THIRD-PARTY-NOTICES.md from the dependency graph.

.DESCRIPTION
    Walks the crates that are linked into the application — the normal
    dependencies of the root package, and theirs in turn — collects the licence
    files each one ships, and groups them so that a text shared by many crates
    is reproduced once. Build-time tools are left out: their output is
    distributed, their code is not.

    Run this whenever the dependency list changes. The result is committed.
#>

[CmdletBinding()]
param(
    [string] $Output = '',
    [string] $Target = ''
)

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Resolve-Path (Join-Path $here '..')
if (-not $Output) { $Output = Join-Path $root 'THIRD-PARTY-NOTICES.md' }
Set-Location $root

# Only the crates that build for the platform being shipped to: the graph
# otherwise carries every other operating system's window and clipboard code,
# none of which is in the binary.
if (-not $Target) {
    $Target = ((& rustc -vV) | Where-Object { $_ -match '^host: ' }) -replace '^host: ', ''
}

Write-Host "Reading the dependency graph for $Target..."
$json = & cargo metadata --format-version 1 --locked --filter-platform $Target
if ($LASTEXITCODE -ne 0) { throw 'cargo metadata failed' }
$meta = $json | ConvertFrom-Json

$nodes = @{}
foreach ($node in $meta.resolve.nodes) { $nodes[$node.id] = $node }

$packages = @{}
foreach ($package in $meta.packages) { $packages[$package.id] = $package }

# Everything reachable from the root through normal dependencies. A dependency
# used only to build (or only to test) never reaches the shipped binary.
$linked = New-Object 'System.Collections.Generic.HashSet[string]'
$queue = New-Object 'System.Collections.Generic.Queue[string]'
$queue.Enqueue($meta.resolve.root)

while ($queue.Count -gt 0) {
    $id = $queue.Dequeue()
    if (-not $linked.Add($id)) { continue }

    foreach ($dep in $nodes[$id].deps) {
        $normal = $false
        foreach ($kind in $dep.dep_kinds) { if ($null -eq $kind.kind) { $normal = $true } }
        if ($normal) { $queue.Enqueue($dep.pkg) }
    }
}

$linked.Remove($meta.resolve.root) | Out-Null
Write-Host "$($linked.Count) crates are linked into the application."

# Each distinct licence text, and who ships it.
$texts = @{}
$rows = @()
$bare = @()

foreach ($id in $linked) {
    $package = $packages[$id]
    $folder = Split-Path $package.manifest_path -Parent
    $named = "$($package.name) $($package.version)"

    $files = @()
    if (Test-Path $folder) {
        $files = Get-ChildItem -Path $folder -File |
            Where-Object { $_.Name -match '^(LICEN[CS]E|COPYING|NOTICE|UNLICENSE)' -and $_.Length -lt 200kb } |
            Sort-Object Name
    }

    $rows += [pscustomobject]@{
        Name    = $package.name
        Version = $package.version
        Licence = if ($package.license) { $package.license } else { 'see the file below' }
    }

    if ($files.Count -eq 0) { $bare += $named; continue }

    foreach ($file in $files) {
        $text = (Get-Content -Raw -Path $file.FullName) -replace "`r`n", "`n"
        $text = $text.Trim()
        if ($text.Length -eq 0) { continue }

        if (-not $texts.ContainsKey($text)) { $texts[$text] = New-Object 'System.Collections.Generic.List[string]' }
        if (-not $texts[$text].Contains($named)) { $texts[$text].Add($named) }
    }
}

$lines = New-Object 'System.Collections.Generic.List[string]'
$lines.Add('# Third-party notices')
$lines.Add('')
$lines.Add('This application is built on the work below, and carries these notices to')
$lines.Add('meet the terms that work is offered under. Generated by `scripts/notices.ps1`;')
$lines.Add('regenerate it whenever the dependency list changes rather than editing it by')
$lines.Add('hand.')
$lines.Add('')
$lines.Add('## PDFium')
$lines.Add('')
$lines.Add('Pages are rasterised by PDFium, licensed under BSD-3-Clause terms with its')
$lines.Add('newer parts under Apache-2.0:')
$lines.Add('')
$lines.Add('> Copyright 2014 The PDFium Authors')
$lines.Add('')
$lines.Add('PDFium is a native library, loaded at run time and not built from this')
$lines.Add('repository. Its full licence travels with it as `PDFIUM-LICENSE.txt`, which')
$lines.Add('the packaging script refuses to build a package without — so whoever receives')
$lines.Add('the application receives the terms the library is offered under, verbatim,')
$lines.Add('rather than a summary of them. A given build may itself include further')
$lines.Add('components under their own terms; the notices shipped with that build govern.')
$lines.Add('')
$lines.Add('## Crates')
$lines.Add('')
$lines.Add("The $($linked.Count) crates linked into the application, with the licence each one declares:")
$lines.Add('')
$lines.Add('| Crate | Version | Licence |')
$lines.Add('| --- | --- | --- |')

foreach ($row in $rows | Sort-Object Name, Version) {
    $lines.Add("| $($row.Name) | $($row.Version) | $($row.Licence) |")
}

if ($bare.Count -gt 0) {
    $lines.Add('')
    $lines.Add('These crates ship no licence file of their own; the terms they declare above')
    $lines.Add('apply, and their texts appear among those below:')
    $lines.Add('')
    foreach ($named in $bare | Sort-Object) { $lines.Add("- $named") }
}

$lines.Add('')
$lines.Add('## Licence texts')
$lines.Add('')
$lines.Add('Each distinct text appears once, with the crates that carry it.')

$ordered = $texts.GetEnumerator() | Sort-Object { -$_.Value.Count }, { $_.Value[0] }

foreach ($entry in $ordered) {
    $lines.Add('')
    $lines.Add('---')
    $lines.Add('')
    foreach ($named in $entry.Value | Sort-Object) { $lines.Add("**$named**  ") }
    $lines.Add('')
    $lines.Add('```')
    foreach ($line in $entry.Key -split "`n") { $lines.Add($line.TrimEnd()) }
    $lines.Add('```')
}

$lines.Add('')

$path = if ([System.IO.Path]::IsPathRooted($Output)) { $Output } else { Join-Path $root $Output }
[System.IO.File]::WriteAllLines($path, $lines, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "Wrote $path — $($texts.Count) distinct licence texts."
